### ISSUE TITLE
我想连接阿里的飞燕平台，连上阿里的MQTT服务器后，如何通知阿里，设备配网已成功？

### ISSUE THREAD

**Issue by 408881465** [legenddcr/aliyun-mqtt-arduino#1]
您好！用你的库连上阿里MQTT服务器后，我想使用阿里的[公版APP控制设备](https://g.alicdn.com/aic/ilop-docs/2018.10.42/yqhcnq.html)
[公版的配网过程](https://g.alicdn.com/aic/ilop-docs/2018.10.42/vb3ia5.html)
如何通知阿里服务器，设备已经配网成功呢？

**Comment by 408881465** [comment]
[整体流程](https://g.alicdn.com/aic/ilop-docs/2018.10.42/vb3ia5.html)
6 设备与云端同步设备绑定的Token
7 设备对外通告用于绑定的Token
步骤中的6、7如何自行实现？

**Comment by legenddcr** [comment]
@408881465 你好，这个库是对连接阿里云MQTT平台的基本功能封装，主要是暂时帮助开发者解决连接需要自己搞定的加密以及配置参数过程。对于和飞燕公版App的配网，并没有开发此功能。

可以稍等一段时间，据我了解阿里方面的Link SDK团队可能会提供一个Arduino上功能比较完善的SDK库，到时候应该就具备配网能力了。

**Comment by 408881465** [comment]
谢谢！
