### ISSUE TITLE
连接阿里MQTT服务器时返回错误代号255

### ISSUE THREAD

**Issue by leon0755** [legenddcr/aliyun-mqtt-arduino#2]
我已经确定三元组的配置没有问题, 但无法连接. 一直返回错误代号255

平台:ESP32
IDE: Arduino

![image](https://user-images.githubusercontent.com/4243081/60093481-1b397500-977c-11e9-9c30-9bba128b2081.png)

**Comment by legenddcr** [comment]
> 我已经确定三元组的配置没有问题, 但无法连接. 一直返回错误代号255
> 
> 平台:ESP32
> IDE: Arduino
> 
> ![image](https://user-images.githubusercontent.com/4243081/60093481-1b397500-977c-11e9-9c30-9bba128b2081.png)

看看有没有加上编译时的build flag，如果没有加是连接不上阿里云IoT平台的。在Hacklab IDE(https://hacklab.aliyun.com)中的例子使用了PlatformIO框架，提前配置好的这些参数。如果使用Arduino IDE和这个库，你需要自己加编译配置参数。具体参数信息见README

**Comment by thomas-void0** [comment]
您好，我使用的是arduino nuo的NB-IOT模块进行阿里云连接，下载了您的库以后。缺少加密的SHA256库，我下载了好几个都不行，请问在哪里可以下载到？
![image](https://user-images.githubusercontent.com/48620706/63234438-cc81f600-c267-11e9-9da3-ec577b24115c.png)

**Comment by craftor** [comment]
> 您好，我使用的是arduino nuo的NB-IOT模块进行阿里云连接，下载了您的库以后。缺少加密的SHA256库，我下载了好几个都不行，请问在哪里可以下载到？
> ![image](https://user-images.githubusercontent.com/48620706/63234438-cc81f600-c267-11e9-9da3-ec577b24115c.png)

install Crypto in Arduino

**Comment by legenddcr** [comment]
https://platformio.org/lib/show/1168/Crypto
