### ISSUE TITLE
MQTT连接失败，错误代码254

### ISSUE THREAD

**Issue by limhGeek** [legenddcr/aliyun-mqtt-arduino#4]
平台:ESP8266-01
IDE: Arduino

我用demo里的例子后一直连接失败，错误代码254，用VSCode一模一样代码压根不执行，串口只输出乱码就没了，不知道咋回事。Arduino IDE的build_flags怎么设置？

**Comment by legenddcr** [comment]
不设置修改PubSubClient库中的默认设置是不行的，最新的情况我没有试过，你可以先直接修改依赖库头文件中的KeepAlive和最大包值先尝试一下能否解决，再具体看看Arduino IDE的文档中如何添加编译选项，最初这个库是用PIO开发的，如果使用VSCode，可以安装PlatformIO插件使用。

**Comment by Liferme** [comment]
> 平台:ESP8266-01
> IDE: Arduino
> 
> 我用demo里的例子后一直连接失败，错误代码254，用VSCode一模一样代码压根不执行，串口只输出乱码就没了，不知道咋回事。Arduino IDE的build_flags怎么设置？

老哥有解决么，我用ESP32也是一直254...

**Comment by limhGeek** [comment]
都多久过去了，我都忘记了怎么弄的，好像没解决，我就是玩玩~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liferme"<notifications@github.com&gt;; 
发送时间: 2020年11月13日(星期五) 上午9:16
收件人: "legenddcr/aliyun-mqtt-arduino"<aliyun-mqtt-arduino@noreply.github.com&gt;; 
抄送: "似水年华"<1591054297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [legenddcr/aliyun-mqtt-arduino] MQTT连接失败，错误代码254 (#4)





  
平台:ESP8266-01
 IDE: Arduino
 
我用demo里的例子后一直连接失败，错误代码254，用VSCode一模一样代码压根不执行，串口只输出乱码就没了，不知道咋回事。Arduino IDE的build_flags怎么设置？
  
老哥有解决么，我用ESP32也是一直254...

**Comment by Liferme** [comment]
好吧，希望楼主可以解决吧，谢谢老哥

**Comment by limhGeek** [comment]
客气了，老铁！我是搞移动APP的，非专业




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liferme"<notifications@github.com&gt;; 
发送时间: 2020年11月13日(星期五) 上午9:35
收件人: "legenddcr/aliyun-mqtt-arduino"<aliyun-mqtt-arduino@noreply.github.com&gt;; 
抄送: "似水年华"<1591054297@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [legenddcr/aliyun-mqtt-arduino] MQTT连接失败，错误代码254 (#4)





 
好吧，希望楼主可以解决吧，谢谢老哥

**Comment by shiwzhi** [comment]
> 不设置修改PubSubClient库中的默认设置是不行的，最新的情况我没有试过，你可以先直接修改依赖库头文件中的KeepAlive和最大包值先尝试一下能否解决，再具体看看Arduino IDE的文档中如何添加编译选项，最初这个库是用PIO开发的，如果使用VSCode，可以安装PlatformIO插件使用。

修改PubSubClient.h中 #define MQTT_KEEPALIVE 15 后连接成功, 阿里云要求:

> CONNECT指令中需包含Keep Alive（保活时间）。保活心跳时间取值范围为30秒~1200秒。如果心跳时间不在此区间内，物联网平台会拒绝连接。建议取值300秒以上。如果网络不稳定，将心跳时间设置高一些。
