### ISSUE TITLE
请问在阿里云上搞过MQTTS吗

### ISSUE THREAD

**Issue by tingyouwu** [legenddcr/aliyun-mqtt-arduino#5]

**Comment by legenddcr** [comment]
阿里云IoT平台之前搞的时候用的是三元组指定加密算法方式来完成认证，当时我印象走的是自己定义的三元组认证方式，最新的情况不是很清楚。另一方面，阿里云IoT平台上重点搞商业化应用方面的东西，对Arduino这样的社区支持得不好
